services:
  web:
    restart: always
    build: .
    command: sh -c "./node_modules/.bin/tsc -p tsconfig.json && ./node_modules/.bin/fastify start -l info app.js"
    volumes:
      - ./:/usr/app/
    ports:
      - "3001:3000"
    env_file:
      - ./.exports
